backend:
  name: github
  repo: a-franca/website
  branch: main
  base_url: https://sveltia-cms-auth.abf-li.workers.dev
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

show_preview_links: false

site_url: https://abf.li
logo_url: https://abf.li/images/feature/brutal-logo.webp

publish_mode: editorial_workflow
media_folder: static/uploads/images
public_folder: uploads/images

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

editor:
  preview: true

collections:

#  - name: "home"
#    label: "Homepage"
#    files:
#      - file: "content/_index.md"
#        label: "_index.md"
#        name: "home"
#        fields:
#          - {label: Title, name: title, widget: string}
#          - {label: Draft, name: draft, widget: boolean}
#          - {label: "Body", name: "body", widget: "markdown"}

#  - name: "posts list"
#    label: "Posts _index"
#    files:
#      - file: "content/posts/_index.md"
#        label: "_index.md"
#        name: "posts list"
#        fields:
#          - {label: Title, name: title, widget: string}
#          - {label: Draft, name: draft, widget: boolean}
#          - {label: "Body", name: "body", widget: "markdown"}

  - name: "post"
    label: "Posts"
    folder: "content/posts"
    path: "{{year}}/{{slug}}/index"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Draft", name: draft, widget: boolean, default: true}
      - {label: "Body", name: "body", widget: "markdown"}

#  - name: "notes list"
#    label: "Notes _index"
#    files:
#      - file: "content/notes/_index.md"
#        label: "_index.md"
#        name: "notes list"
#        fields:
#          - {label: Title, name: title, widget: string}
#          - {label: Draft, name: draft, widget: boolean}
#          - {label: "Body", name: "body", widget: "markdown"}

  - name: "notes"
    label: "Notes"
    folder: "content/notes"
    path: "{{year}}/{{year}}{{month}}{{day}}-{{hour}}{{minute}}/index"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", default: "dd Month YYYY at hh:mm"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["notes"], required: false}
      - {label: "Draft", name: draft, widget: boolean, default: false}
      - {label: "Body", name: "body", widget: "markdown"}

#  - name: "pages list"
#    label: "Pages _index"
#    files:
#      - file: "content/pages/_index.md"
#        label: "_index"
#        name: "pages list"
#        fields:
#          - {label: Title, name: title, widget: string}
#          - {label: Draft, name: draft, widget: boolean}
#          - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    path: "{{slug}}/index"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: draft, widget: boolean, default: true}
      - {label: "Body", name: "body", widget: "markdown"}